ARG UBUNTU_VERSION="24.04"

FROM ubuntu:${UBUNTU_VERSION}

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libblas-dev \
        liblapack-dev \
        python3-dev \
        python3-pip \
        python-is-python3 \
        python3-venv \
        git \
        build-essential && \
    rm -rf /var/lib/apt/lists/*

RUN python -m venv /opt/venv
# Enable venv
ENV PATH="/opt/venv/bin:$PATH"
