
// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.11.0.dev0.
//
// This code was generated with the following options:
//
//  {'dir': '.',
//   'epsilon': 1e-14,
//   'language': 'ffcx_backends.cpp',
//   'part': 'full',
//   'profile': False,
//   'scalar_type': 'float64',
//   'sum_factorization': False,
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'ufl_file': ['Poisson1D.py'],
//   'verbosity': 30,
//   'visualise': False}

#pragma once

#include <complex>
#include <cstdint>
#include <cmath>
#include <vector>

#include "ufcx.h"

#if defined(_MSC_VER)
#   define RESTRICT __restrict
#else
#   define RESTRICT __restrict__
#endif
    
class integral_d8fa5e718faa9ffc04ecc9d9892181eee21a0173
{
public:

// Constructor
integral_d8fa5e718faa9ffc04ecc9d9892181eee21a0173();

// Kernel
template <typename T, typename U>
void tabulate_tensor(T* A,
                     const T* RESTRICT w,
                     const T* RESTRICT c,
                     const U* RESTRICT coordinate_dofs,
                     const std::int32_t* RESTRICT entity_local_index,
                     const std::uint8_t* RESTRICT quadrature_permutation);

// Data
std::vector<bool> enabled_coefficients; // TODO: std::vector<char>?
bool needs_facet_permutations;

};

// Code for integral integral_d8fa5e718faa9ffc04ecc9d9892181eee21a0173

template <typename T, typename U>
void integral_d8fa5e718faa9ffc04ecc9d9892181eee21a0173::tabulate_tensor(T* RESTRICT A,
                     const T* RESTRICT w,
                     const T* RESTRICT c,
                     const U* RESTRICT coordinate_dofs,
                     const std::int32_t* RESTRICT entity_local_index,
                     const std::uint8_t* RESTRICT quadrature_permutation)
{
// Quadrature rules
static const U weights_ecb[1] = {1.0};
// Precomputed values of basis functions and precomputations
// FE* dimensions: [permutation][entities][points][dofs]
static const U FE0_C0_D1_Qecb[1][1][1][2] = {{{{-1.0, 1.0}}}};
// ------------------------ 
// Section: Jacobian
// Inputs: FE0_C0_D1_Qecb, coordinate_dofs
// Outputs: J0_c0
U J0_c0 = 0.0;
{
  for (int ic = 0; ic < 2; ++ic)
  {
    J0_c0 += coordinate_dofs[(ic) * 3] * FE0_C0_D1_Qecb[0][0][0][ic];
  }
}
// ------------------------ 
U sp_ecb_0 = 1.0 / J0_c0;
U sp_ecb_1 = sp_ecb_0 * sp_ecb_0;
U sp_ecb_2 = std::abs(J0_c0);
U sp_ecb_3 = sp_ecb_1 * sp_ecb_2;
for (int iq = 0; iq < 1; ++iq)
{
  // ------------------------ 
  // Section: Intermediates
  // Inputs: 
  // Outputs: fw0
  T fw0 = 0;
  {
    fw0 = sp_ecb_3 * weights_ecb[iq];
  }
  // ------------------------ 
  // ------------------------ 
  // Section: Tensor Computation
  // Inputs: FE0_C0_D1_Qecb, fw0
  // Outputs: A
  {
    T temp_0[2] = {0};
    for (int j = 0; j < 2; ++j)
    {
      temp_0[j] = fw0 * FE0_C0_D1_Qecb[0][0][0][j];
    }
    for (int j = 0; j < 2; ++j)
    {
      for (int i = 0; i < 2; ++i)
      {
        A[2 * (i) + (j)] += FE0_C0_D1_Qecb[0][0][0][i] * temp_0[j];
      }
    }
  }
  // ------------------------ 
}

}

integral_d8fa5e718faa9ffc04ecc9d9892181eee21a0173::integral_d8fa5e718faa9ffc04ecc9d9892181eee21a0173()
{
  enabled_coefficients = {};
  needs_facet_permutations = false;
}

// End of code for integral integral_d8fa5e718faa9ffc04ecc9d9892181eee21a0173

class integral_a11e991096b4f4835cec4cbb06fff420d3428714
{
public:

// Constructor
integral_a11e991096b4f4835cec4cbb06fff420d3428714();

// Kernel
template <typename T, typename U>
void tabulate_tensor(T* A,
                     const T* RESTRICT w,
                     const T* RESTRICT c,
                     const U* RESTRICT coordinate_dofs,
                     const std::int32_t* RESTRICT entity_local_index,
                     const std::uint8_t* RESTRICT quadrature_permutation);

// Data
std::vector<bool> enabled_coefficients; // TODO: std::vector<char>?
bool needs_facet_permutations;

};

// Code for integral integral_a11e991096b4f4835cec4cbb06fff420d3428714

template <typename T, typename U>
void integral_a11e991096b4f4835cec4cbb06fff420d3428714::tabulate_tensor(T* RESTRICT A,
                     const T* RESTRICT w,
                     const T* RESTRICT c,
                     const U* RESTRICT coordinate_dofs,
                     const std::int32_t* RESTRICT entity_local_index,
                     const std::uint8_t* RESTRICT quadrature_permutation)
{
// Quadrature rules
static const U weights_4a8[2] = {0.5, 0.5};
// Precomputed values of basis functions and precomputations
// FE* dimensions: [permutation][entities][points][dofs]
static const U FE0_C0_Q4a8[1][1][2][2] = {{{{0.7886751345948129, 0.2113248654051871},
{0.2113248654051871, 0.7886751345948129}}}};
static const U FE1_C0_D1_Q4a8[1][1][1][2] = {{{{-1.0, 1.0}}}};
// ------------------------ 
// Section: Jacobian
// Inputs: coordinate_dofs, FE1_C0_D1_Q4a8
// Outputs: J0_c0
U J0_c0 = 0.0;
{
  for (int ic = 0; ic < 2; ++ic)
  {
    J0_c0 += coordinate_dofs[(ic) * 3] * FE1_C0_D1_Q4a8[0][0][0][ic];
  }
}
// ------------------------ 
U sp_4a8_0 = std::abs(J0_c0);
for (int iq = 0; iq < 2; ++iq)
{
  // ------------------------ 
  // Section: Coefficient
  // Inputs: FE0_C0_Q4a8, w
  // Outputs: w0
  T w0 = 0.0;
  {
    for (int ic = 0; ic < 2; ++ic)
    {
      w0 += w[ic] * FE0_C0_Q4a8[0][0][iq][ic];
    }
  }
  // ------------------------ 
  // ------------------------ 
  // Section: Intermediates
  // Inputs: w0
  // Outputs: fw0
  T fw0 = 0;
  {
    T sv_4a8_0 = sp_4a8_0 * w0;
    fw0 = sv_4a8_0 * weights_4a8[iq];
  }
  // ------------------------ 
  // ------------------------ 
  // Section: Tensor Computation
  // Inputs: FE0_C0_Q4a8, fw0
  // Outputs: A
  {
    for (int i = 0; i < 2; ++i)
    {
      A[(i)] += fw0 * FE0_C0_Q4a8[0][0][iq][i];
    }
  }
  // ------------------------ 
}

}

integral_a11e991096b4f4835cec4cbb06fff420d3428714::integral_a11e991096b4f4835cec4cbb06fff420d3428714()
{
  enabled_coefficients = {true};
  needs_facet_permutations = false;
}

// End of code for integral integral_a11e991096b4f4835cec4cbb06fff420d3428714

    extern ufcx_form form_717d6c9c28d26ac3ca92aeb49bede4a5d4f6ce92;

    // Helper used to create form using name which was given to the
    // form in the UFL file.
    // This helper is called in user c++ code.
    //
    extern ufcx_form* form_Poisson1D_a;

    
    // Code for form form_717d6c9c28d26ac3ca92aeb49bede4a5d4f6ce92

    // TODO: that correct?
    
    uint64_t finite_element_hashes_form_717d6c9c28d26ac3ca92aeb49bede4a5d4f6ce92[2] = {UINT64_C(16933918038099048440), UINT64_C(16933918038099048440)};
    int form_integral_offsets_form_717d6c9c28d26ac3ca92aeb49bede4a5d4f6ce92[6] = {0, 1, 1, 1, 1, 1};
    static ufcx_integral* form_integrals_form_717d6c9c28d26ac3ca92aeb49bede4a5d4f6ce92[1] = {&integral_d8fa5e718faa9ffc04ecc9d9892181eee21a0173_interval};
    int form_integral_ids_form_717d6c9c28d26ac3ca92aeb49bede4a5d4f6ce92[1] = {-1};

    
    
    
    

    form_Poisson1D_a::signature ="1628406adf1dea543a9f5a417235f9ab31c8d9acf2ea5ed76ff49b56aae202ca7be522ce35a7e1c1ab7dcf15b684fb64d33a2ab15e7fe44268a70704e9dfd42e";
    form_Poisson1D_a::rank = 2;

    form_Poisson1D_a::num_coefficients = 0;
    form_Poisson1D_a::original_coefficient_positions = NULL;
    form_Poisson1D_a::coefficient_name_map = NULL;

    form_Poisson1D_a::num_constants = 0;
    form_Poisson1D_a::constant_ranks = NULL;
    form_Poisson1D_a::constant_shapes = NULL;
    form_Poisson1D_a::constant_name_map = NULL;

    form_Poisson1D_a::finite_element_hashes = finite_element_hashes_form_717d6c9c28d26ac3ca92aeb49bede4a5d4f6ce92,

    form_Poisson1D_a::form_integrals = form_integrals_form_717d6c9c28d26ac3ca92aeb49bede4a5d4f6ce92;
    form_Poisson1D_a::form_integral_ids = form_integral_ids_form_717d6c9c28d26ac3ca92aeb49bede4a5d4f6ce92;
    form_Poisson1D_a::form_integral_offsets = form_integral_offsets_form_717d6c9c28d26ac3ca92aeb49bede4a5d4f6ce92;

    // Alias name
    using form_Poisson1D_a = form_717d6c9c28d26ac3ca92aeb49bede4a5d4f6ce92;

    // End of code for form form_717d6c9c28d26ac3ca92aeb49bede4a5d4f6ce92
    
    extern ufcx_form form_b657499bcce5182aee57b1310625642b46198539;

    // Helper used to create form using name which was given to the
    // form in the UFL file.
    // This helper is called in user c++ code.
    //
    extern ufcx_form* form_Poisson1D_L;

    
    // Code for form form_b657499bcce5182aee57b1310625642b46198539

    // TODO: that correct?
    int original_coefficient_position_form_b657499bcce5182aee57b1310625642b46198539[1] = {0};
    uint64_t finite_element_hashes_form_b657499bcce5182aee57b1310625642b46198539[2] = {UINT64_C(16933918038099048440), UINT64_C(16933918038099048440)};
    int form_integral_offsets_form_b657499bcce5182aee57b1310625642b46198539[6] = {0, 1, 1, 1, 1, 1};
    static ufcx_integral* form_integrals_form_b657499bcce5182aee57b1310625642b46198539[1] = {&integral_a11e991096b4f4835cec4cbb06fff420d3428714_interval};
    int form_integral_ids_form_b657499bcce5182aee57b1310625642b46198539[1] = {-1};

    static const char* coefficient_names_form_b657499bcce5182aee57b1310625642b46198539[1] = {"f"};
    
    
    

    form_Poisson1D_L::signature ="a77cbccf1c3607c9029661a2491bff2fc518a6ce15848b364dad1228322e2f2c0cae6bb480567fcd2ff24b3673af5b67eb85a3611f1a4aff438f6799a55cbf0f";
    form_Poisson1D_L::rank = 1;

    form_Poisson1D_L::num_coefficients = 1;
    form_Poisson1D_L::original_coefficient_positions = original_coefficient_position_form_b657499bcce5182aee57b1310625642b46198539;
    form_Poisson1D_L::coefficient_name_map = coefficient_names_form_b657499bcce5182aee57b1310625642b46198539;

    form_Poisson1D_L::num_constants = 0;
    form_Poisson1D_L::constant_ranks = NULL;
    form_Poisson1D_L::constant_shapes = NULL;
    form_Poisson1D_L::constant_name_map = NULL;

    form_Poisson1D_L::finite_element_hashes = finite_element_hashes_form_b657499bcce5182aee57b1310625642b46198539,

    form_Poisson1D_L::form_integrals = form_integrals_form_b657499bcce5182aee57b1310625642b46198539;
    form_Poisson1D_L::form_integral_ids = form_integral_ids_form_b657499bcce5182aee57b1310625642b46198539;
    form_Poisson1D_L::form_integral_offsets = form_integral_offsets_form_b657499bcce5182aee57b1310625642b46198539;

    // Alias name
    using form_Poisson1D_L = form_b657499bcce5182aee57b1310625642b46198539;

    // End of code for form form_b657499bcce5182aee57b1310625642b46198539
    
    