"""Templates for generated CUDA UFCx code."""

metadata_factory = """
// This code conforms to the UFCx specification version {ufcx_version}
// and was automatically generated by FFCx version {ffcx_version}.
//
// This code was generated with the following options:
//
{options}

#include <ufcx.h>
"""

kernel_factory = """
// This code conforms to the UFCx specification version {ufcx_version}
// and was automatically generated by FFCx version {ffcx_version}.
//
// This code was generated with the following options:
//
{options}

#define alignas(x)
#define restrict __restrict__

typedef unsigned char uint8_t;
typedef unsigned int uint32_t;
typedef double ufc_scalar_t;

"""
